name: Test my Action Repo
on:
  workflow_dispatch:

jobs:
  test_my_action:
    runs-on: ubuntu-latest
    steps:
      - uses: andrewarosario/semantic-release-example@v1.0.0
        with:
          person: 'Thom Yorke'
